begin;

with team_seed(full_name, sort_order) as (
  values
    ('Iain Haycock', 1),
    ('Andrew Dick', 2),
    ('Grant Restall', 3),
    ('Tracey Flatman', 4),
    ('Emma Vermeulen', 5),
    ('Esther Hislop', 6),
    ('Harley Winchester', 7),
    ('Gearld Bennett', 8),
    ('Zac Luxton', 9),
    ('Karl Jackson', 10),
    ('Bob Orchard', 11),
    ('Bevin Jones', 12),
    ('Johan Bekker', 13),
    ('Grant McGregor', 14),
    ('Andy Gibellini', 15),
    ('Alan Harkerss', 16),
    ('Quin Hainsworth', 17),
    ('Ed Purcell', 18),
    ('Melandro Cena', 19),
    ('Colin Charleston', 20),
    ('Paul Smith', 21),
    ('David Kiesanowski', 22),
    ('Tyler Ward', 23),
    ('Jai Winsloe', 24),
    ('Shodie Milne', 25),
    ('Sam Stevenson', 26),
    ('Declan Hogan', 27),
    ('Mohsen Ghaedi', 28),
    ('Qwin Billings', 29),
    ('Arthur Bass', 30),
    ('Sean Templeton', 31),
    ('Tom Lubbe', 32),
    ('Greg Cossar', 33),
    ('Kortni Morris', 34),
    ('Paul Taulava', 35),
    ('Edwin Diaz', 36),
    ('Brian McMahon', 37),
    ('Ben Wilson', 38),
    ('Rian Gibson', 39),
    ('Josh Phillips', 40),
    ('Christian Yee', 41),
    ('Phil McSweeney', 42),
    ('Marty Beijen', 43),
    ('Harley Wards', 44),
    ('Nuni Lasike', 45),
    ('Harrison Dick', 46),
    ('Gerald Handcock', 47),
    ('Kim Kelly', 48),
    ('John Oliver', 49),
    ('Ash Mills', 50),
    ('Long Nguyen', 51),
    ('Sam Dissanayake', 52),
    ('Dave Larsen', 53),
    ('Donald Anderson', 54),
    ('Phil Blackbourn', 55),
    ('Sione Inoke', 56),
    ('Nigel Swindles', 57),
    ('Robbie Grant', 58),
    ('Iain Cooling', 59),
    ('Murray Standen', 60),
    ('Caleb Rack', 61),
    ('Caleb Hawken', 62),
    ('Shiloh Fountain', 63),
    ('Craig Kennedy', 64),
    ('Jeremy Cain', 65),
    ('Jaz Moana', 66),
    ('Royden Rapana', 67),
    ('Ben Scurry', 68),
    ('Chris Paki', 69),
    ('Lea Fehoko', 70),
    ('Akashdeep Singh', 71),
    ('Rahul Negi', 72),
    ('Lei Vehikite', 73),
    ('James Ludwig', 74),
    ('Flynn Llelliot', 75),
    ('Rick McNaughton', 76),
    ('Albert Ngata', 77),
    ('Josh Tonga', 78),
    ('Patrick Gurney', 79),
    ('Kenny Losaki', 80),
    ('Quddus', 81),
    ('Haydn Coley', 82),
    ('Regan Waterreus', 83),
    ('Jordyn Edmonds', 84),
    ('Lexus Bates', 85),
    ('Gregory Capper Conjin', 86),
    ('Cewade DeThierry', 87),
    ('Hayden Rawiri', 88),
    ('Codey Rack', 89),
    ('Shannon Hartley', 90),
    ('Steve Hoban', 91),
    ('Johan Venter', 92)
)
insert into app_users (
  employee_code,
  full_name,
  initials,
  role_title,
  app_role,
  division,
  region,
  metadata
)
select
  'TEAM-' || lpad(sort_order::text, 3, '0'),
  full_name,
  upper(
    left(split_part(full_name, ' ', 1), 1) ||
    coalesce(left(nullif(split_part(full_name, ' ', 2), ''), 1), '')
  ),
  'Team Member',
  'FieldUser',
  null,
  null,
  jsonb_build_object('source', 'teamlist.txt')
from team_seed
where not exists (
  select 1
  from app_users existing
  where lower(existing.full_name) = lower(team_seed.full_name)
);

commit;
